name: Alerta Discord

on:
  push:
    branches: [ "main" ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar alerta para Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"Novo commit realizado\nAutor: ${{ github.actor }}\nRepositorio: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nMensagem: ${{ github.event.head_commit.message }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
